# See the documentation for all available configuration options
joli_media:
    # Configure a media library below. See the documentation for all available options
    # at https://mediabundle.jolicode.com/getting-started/configuration/#configuration

    default_library: default

    processors:
        imagine:
            driver: gd
            options:
                jpeg_quality: 85
                png_quality: 80
                quality: 85

    libraries:
        default:
            original:
                flysystem: 'filesystem.original.storage'
                url_generator:
                    strategy: folder
                    path: /media/original/
            cache:
                flysystem: 'filesystem.cache.storage'
                must_store_when_generating_url: true
                url_generator:
                    strategy: folder
                    path: /media/cache/

            enable_auto_webp: true

            variations:
                thumbnail:
                    transformers:
                        resize:
                            width: 200
                            height: 200
                            mode: inside
                            allow_upscale: false
                medium:
                    transformers:
                        resize:
                            width: 800
                            height: 600
                            mode: inside
                large:
                    transformers:
                        resize:
                            width: 1920
                            height: 1080
                            mode: inside

    pre_processors:
        - JoliCode\MediaBundle\PreProcessor\ExifRemovalPreProcessor
