# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

#controllers:
#    resource: routing.controllers
#    prefix: /{_locale}
#    defaults:
#        _locale: '%app.locale%'

root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: 'app_home'
        permanent: true   # Redirection 301 (Bon pour le SEO)
        _locale: 'fr'     # Force la locale par d√©faut

controllers_public:
    resource:
        path: ../src/Controller/
        namespace: ADS\UCCIA\Controller
    # exclude: ../src/Controller/Admin/
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: 'fr|en|ar'
    defaults:
        _locale: '%app.locale%'
    schemes:
        - HTTPS

controllers_admin:
    resource:
        path: ../src/Controller/Admin/
        namespace: ADS\UCCIA\Controller\Admin # Attention au namespace qui change !
    type: attribute
    # Pas de prefix ou un prefix fixe comme /admin
    # prefix: /admin
    schemes:
        - HTTPS
